# Support Vector Machine

Al igual que vimos antes, el algoritmo SVM nos ayuda a clasificar observaciones en distintas categorías encontrando la frontera más grande entre ambas categorías (support vector). Ya vimos en la presentación qué es lo que hace, así que implementémoslo sobre la misma base de spotify que teníamos, y luego probemos con alguna otra base de datos.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
spotify = pd.read_csv('data_spotify.csv')
spotify = spotify.iloc[:, 1:]
spotify.head()

acousticness  danceability  duration_ms  energy  instrumentalness  key  \
0        0.0102         0.833       204600   0.434          0.021900    2   
1        0.1990         0.743       326933   0.359          0.006110    1   
2        0.0344         0.838       185707   0.412          0.000234    2   
3        0.6040         0.494       199413   0.338          0.510000    5   
4        0.1800         0.678       392893   0.561          0.512000    5   

   liveness  loudness  mode  speechiness    tempo  time_signature  valence  \
0    0.1650    -8.795     1       0.4310  150.062             4.0    0.286   
1    0.1370   -10.401     1       0.0794  160.083             4.0    0.588   
2    0.1590    -7.148     1       0.2890   75.044             4.0    0.173   
3    0.0922   -15.236     1       0.0261   86.468             4.0    0.230   
4    0.4390   -11.648     0       0.0694  174.004             4.0    0.904   

   target      song_title            artist  
0       1        Mask Off            Future  
1       1         Redbone  Childish Gambino  
2       1    Xanny Family            Future  
3       1  Master Of None       Beach House  
4       1  Parallel Lines       Junior Boys

In [ ]:
spotify.describe()

acousticness  danceability   duration_ms       energy  \
count   2017.000000   2017.000000  2.017000e+03  2017.000000   
mean       0.187590      0.618422  2.463062e+05     0.681577   
std        0.259989      0.161029  8.198181e+04     0.210273   
min        0.000003      0.122000  1.604200e+04     0.014800   
25%        0.009630      0.514000  2.000150e+05     0.563000   
50%        0.063300      0.631000  2.292610e+05     0.715000   
75%        0.265000      0.738000  2.703330e+05     0.846000   
max        0.995000      0.984000  1.004627e+06     0.998000   

       instrumentalness          key     liveness     loudness         mode  \
count       2017.000000  2017.000000  2017.000000  2017.000000  2017.000000   
mean           0.133286     5.342588     0.190844    -7.085624     0.612295   
std            0.273162     3.648240     0.155453     3.761684     0.487347   
min            0.000000     0.000000     0.018800   -33.097000     0.000000   
25%            0.000000     2.000000     0.092300    -8.394000     0.000000   
50%            0.000076     6.000000     0.127000    -6.248000     1.000000   
75%            0.054000     9.000000     0.247000    -4.746000     1.000000   
max            0.976000    11.000000     0.969000    -0.307000     1.000000   

       speechiness        tempo  time_signature      valence       target  
count  2017.000000  2017.000000     2017.000000  2017.000000  2017.000000  
mean      0.092664   121.603272        3.968270     0.496815     0.505702  
std       0.089931    26.685604        0.255853     0.247195     0.500091  
min       0.023100    47.859000        1.000000     0.034800     0.000000  
25%       0.037500   100.189000        4.000000     0.295000     0.000000  
50%       0.054900   121.427000        4.000000     0.492000     1.000000  
75%       0.108000   137.849000        4.000000     0.691000     1.000000  
max       0.816000   219.331000        5.000000     0.992000     1.000000

In [ ]:
spotify.shape

(2017, 16)

In [ ]:
X = spotify.iloc[:, :13]
X.head()

acousticness  danceability  duration_ms  energy  instrumentalness  key  \
0        0.0102         0.833       204600   0.434          0.021900    2   
1        0.1990         0.743       326933   0.359          0.006110    1   
2        0.0344         0.838       185707   0.412          0.000234    2   
3        0.6040         0.494       199413   0.338          0.510000    5   
4        0.1800         0.678       392893   0.561          0.512000    5   

   liveness  loudness  mode  speechiness    tempo  time_signature  valence  
0    0.1650    -8.795     1       0.4310  150.062             4.0    0.286  
1    0.1370   -10.401     1       0.0794  160.083             4.0    0.588  
2    0.1590    -7.148     1       0.2890   75.044             4.0    0.173  
3    0.0922   -15.236     1       0.0261   86.468             4.0    0.230  
4    0.4390   -11.648     0       0.0694  174.004             4.0    0.904

In [ ]:
y = spotify.target
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

Recuerden que es importante que reescalemos nuestras variables! Pero primero hay que dividir nuestra base

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(X_train)
scaler.fit(X_train)

      acousticness  danceability  duration_ms  energy  instrumentalness  key  \
1176      0.002460         0.532       200733  0.7780          0.000111    7   
621       0.002210         0.632       156614  0.7930          0.000000   10   
748       0.009690         0.589       323480  0.6210          0.001040    5   
195       0.613000         0.698       230200  0.8780          0.000016    8   
354       0.270000         0.446       259765  0.8900          0.661000    7   
1853      0.009470         0.739       261933  0.9470          0.000030   11   
415       0.034000         0.691       425320  0.7100          0.002250   10   
1719      0.000479         0.695       218187  0.5790          0.000000    0   
1597      0.971000         0.338       455307  0.0539          0.328000    9   
245       0.062600         0.697       181149  0.6550          0.774000    1   
1559      0.717000         0.423       335333  0.1580          0.007500    0   
1889      0.006700         0.420       2

/home/azu/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
print(X_train)

[[-0.70802802 -0.56648285 -0.56010117 ...  1.8478352   0.11302655
  -1.0190227 ]
 [-0.70898385  0.06376307 -1.09839863 ...  2.61060676  0.11302655
  -0.40697638]
 [-0.68038534 -0.20724268  0.93753925 ...  0.71167844  0.11302655
  -0.38670995]
 ...
 [-0.63102615 -0.22615005 -0.39546041 ...  0.40830296  0.11302655
   0.11995091]
 [ 0.34545231  0.59316964 -0.49827853 ...  0.59248707  0.11302655
   1.70883935]
 [-0.70603989 -0.48455088  0.38540582 ...  0.70563526  0.11302655
   0.76037023]]


/home/azu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.
/home/azu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  


In [ ]:
from sklearn.svm import SVC

svclassifier = SVC(kernel='linear')

svclassifier.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(X_test)
y_pred

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[137  60]
 [ 87 120]]
              precision    recall  f1-score   support

           0       0.61      0.70      0.65       197
           1       0.67      0.58      0.62       207

   micro avg       0.64      0.64      0.64       404
   macro avg       0.64      0.64      0.64       404
weighted avg       0.64      0.64      0.64       404



In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print('DecisionTreeClassifier accuracy score: {}'.format(accuracy))

DecisionTreeClassifier accuracy score: 0.6361386138613861


## Probemos si no es porque la solución no es lineal

In [ ]:
svclassifier = SVC(kernel='poly', degree = 3)

svclassifier.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(X_test)
y_pred

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,

In [ ]:
accuracy_score(y_test, y_pred)

0.7004950495049505

In [ ]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[162  35]
 [ 86 121]]
              precision    recall  f1-score   support

           0       0.65      0.82      0.73       197
           1       0.78      0.58      0.67       207

   micro avg       0.70      0.70      0.70       404
   macro avg       0.71      0.70      0.70       404
weighted avg       0.72      0.70      0.70       404



**¿Mejoró**, pero esto qué me dice? ¿Qué hay de la C?

In [ ]:
svclassifier = SVC(kernel='poly', degree = 3, C=3)

svclassifier.fit(X_train, y_train) 

SVC(C=3, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

0.7079207920792079

Recuerden que lo que hicimos al aumentar la C de 1 a 3 lo que sucedió fue que la "calle" se hizo más angosta y con ello permitió menos violaciones a la frontera. ¿Qué problemas tiene esto? ¿Qué ventajas?

Probemos también otros kernels, no sólo el que "agrega" polinomios

In [ ]:
svclassifier = SVC(kernel='rbf') # kernel gaussiano

svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

accuracy_score(y_test, y_pred)

0.7425742574257426

In [ ]:
svclassifier = SVC(kernel='sigmoid') # kernel sigmoid

svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

accuracy_score(y_test, y_pred)

0.5420792079207921

## Parece que el gaussiano funciono. Por?

In [ ]:
svclassifier = SVC(kernel='rbf') # kernel gaussiano

svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

accuracy_score(y_test, y_pred)

0.7599009900990099

### Estos claramente no son nuestros datos, porque nosotros netemos N dimensiones, pero es para entender qué pasa. El kernel gaussiano lo que hace es poner los datos en una distribución Gaussiana (como de campana, normal) para separar las categorías.

<img src="GaussKernel.png">

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

<img src="GaussKernel2.png">