In [ ]:
from typing import List
import numpy as np
import math

#Vectores

In [ ]:
vector = List[float]

v = [1.70,  # metros,
     75,   # kilos,
     40 ]  # años

#v = [1.70, 75, 40]

w = [95,   # exam1
     80,    # exam2
     75 ]   # exam3

In [ ]:
type(v)

list

In [ ]:
type(w)

list

#Matrices

In [ ]:
matrix = List[List[float]]

A = [[1, 2, 3],  # A tiene 2 filas y 3 columnas
     [4, 5, 6]]

B = [[1, 2],     # B tiene 3 filas y 2 columnas
     [3, 4],
     [5, 6]]

#Operaciones 

In [37]:
def prod_punto(v,w):
  return sum(v_i * w_i for v_i, w_i in zip(v, w))

In [ ]:
v

[1.7, 75, 40]

In [ ]:
w

[95, 80, 75]

In [ ]:
for v_i, w_i in zip(v, w):
  print(v_i, w_i)

1.7 95
75 80
40 75


In [ ]:
[v_i * w_i for v_i, w_i in zip(v, w)]

[161.5, 6000, 3000]

In [ ]:
sum([v_i * w_i for v_i, w_i in zip(v, w)])

9161.5

In [ ]:
prod_punto(v,w)

9161.5

In [ ]:
distancia(v,w)

95.71572493587456

In [ ]:
A+B

[[1, 2, 3], [4, 5, 6], [1, 2], [3, 4], [5, 6]]

In [ ]:
arrayA = np.array(A)
arrayB = np.array(B)

type(arrayA), type(arrayB)

(numpy.ndarray, numpy.ndarray)

In [ ]:
arrayA + arrayA

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
A*B  #?? se puede

TypeError: ignored

In [ ]:
arrayA * arrayB

ValueError: ignored

In [ ]:
arrayA * arrayB.T

array([[ 1,  6, 15],
       [ 8, 20, 36]])

In [ ]:
arrayB

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arrayB.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
np.transpose(arrayB)

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
np.matmul(arrayA, arrayB)

array([[22, 28],
       [49, 64]])