# Challenge

1. Genera cuatro matrices, una de (5x3), (3,5), (9x9),(2x2)
de todas las matrices obtén sus matrices transpuestas y multiplicalas.

In [ ]:
import numpy as np

In [ ]:
np.random.randn(4)

array([-1.08084798,  0.19289129,  0.42652407, -0.18180951])

In [ ]:
np.random.randn(3,2)

array([[-0.26998352, -0.3438187 ],
       [ 1.64282262,  0.52748731],
       [-0.08202535, -0.63106238]])

In [ ]:
A = np.random.randn(5,3)
B = np.random.randn(3,5)
C = np.random.randn(9,9)
D = np.random.randn(2,2)

In [ ]:
A

array([[ 1.66716857,  0.04959553, -0.05188665],
       [-0.15082809, -2.1952747 ,  2.49023307],
       [-0.06633289,  0.35888244, -0.34866603],
       [ 0.42241006, -1.71626925, -0.53042643],
       [ 0.43092888,  0.00364586, -0.88767534]])

In [ ]:
A.T

array([[ 1.66716857, -0.15082809, -0.06633289,  0.42241006,  0.43092888],
       [ 0.04959553, -2.1952747 ,  0.35888244, -1.71626925,  0.00364586],
       [-0.05188665,  2.49023307, -0.34866603, -0.53042643, -0.88767534]])

In [ ]:
M1 = np.matmul(A, A.T)
M2 = np.matmul(B, B.T)
M3 = np.matmul(C, C.T)
M4 = np.matmul(D, D.T)

In [ ]:
M1

array([[ 2.78460299, -0.48954152, -0.07469802,  0.64663154,  0.76467041],
       [-0.48954152, 11.0432409 , -1.64610034,  2.38308574, -2.28351832],
       [-0.07469802, -1.64610034,  0.25476465, -0.4590169 ,  0.28222591],
       [ 0.64663154,  2.38308574, -0.4590169 ,  3.40536258,  0.64661788],
       [ 0.76467041, -2.28351832,  0.28222591,  0.64661788,  0.9736805 ]])

In [ ]:
M2

array([[ 2.99801287, -2.71665688,  2.90088345],
       [-2.71665688,  4.62086613, -3.96057884],
       [ 2.90088345, -3.96057884, 10.48889658]])

In [ ]:
M3

array([[ 5.67850075,  0.64533425, -0.14963507,  1.10587672,  4.89994665,
         0.88598833, -1.93069998,  2.59116934,  1.694752  ],
       [ 0.64533425,  2.54085593, -0.5093723 ,  1.77902161,  1.92644472,
        -2.28301609, -0.02264268, -0.08533518,  0.46343724],
       [-0.14963507, -0.5093723 ,  4.09673924,  5.1407775 , -1.29416251,
        -1.50059495, -0.56649999,  1.25203756,  0.67726207],
       [ 1.10587672,  1.77902161,  5.1407775 , 13.39519384,  1.92233088,
        -0.21003817, -0.42233497, -2.79805534,  1.428685  ],
       [ 4.89994665,  1.92644472, -1.29416251,  1.92233088, 13.31354581,
         2.3796584 , -0.73110257,  2.21531339, -2.02887905],
       [ 0.88598833, -2.28301609, -1.50059495, -0.21003817,  2.3796584 ,
        13.95021652, -3.61373337, -1.62525908, -3.28236127],
       [-1.93069998, -0.02264268, -0.56649999, -0.42233497, -0.73110257,
        -3.61373337,  7.08104371, -3.22038545,  1.15189866],
       [ 2.59116934, -0.08533518,  1.25203756, -2.79805534,  2

In [ ]:
M4

array([[ 0.93258584, -0.87383053],
       [-0.87383053,  1.70595456]])

2. Genera tres vectores  de 4 elementos, realiza los productos punto entre todos ellos.

In [ ]:
V1 = np.random.randn(4)
V2 = np.random.randn(4)
V3 = np.random.randn(4)

In [ ]:
print(V1)
print(V2)
print(V3)

[-1.43547314  0.22059783 -1.64513747 -0.06673431]
[-2.01555681  0.1370454   0.43256334  1.23586811]
[ 0.67499147  0.18451663 -1.32233935 -0.40035437]


In [ ]:
def prod_punto(v,w):
  return sum(v_i * w_i for v_i, w_i in zip(v, w))

In [ ]:
prod_punto(V1, V2)

2.1294086240949586

In [ ]:
np.dot(V1, V2)

2.129408624094959

3. Obtén una matriz identidad de (8x8)

In [ ]:
I4 = np.identity(4)

In [ ]:
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
I5 = np.identity(5)

In [ ]:
I5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
I8 = np.identity(8)

In [ ]:
print(I8)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
x = 7.25
x

7.25

In [ ]:
y = [1, 2, 3]
y

[1, 2, 3]

In [ ]:
z = {'a': 1, 'b': 3}
z

{'a': 1, 'b': 3}